openapi: 3.0.3
info:
  title: Real-Time Register Change Detection WebSocket API
  version: 1.0.0
  description: WebSocket protocol extension for real-time Modbus register change detection

components:
  schemas:
    RegisterChangeEvent:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the change event
          example: "change_20231027_143052_1001"
        registerAddress:
          type: integer
          minimum: 1
          maximum: 65535
          description: Modbus register address
          example: 1001
        oldValue:
          type: number
          nullable: true
          description: Previous register value (null for first reading)
          example: 23.5
        newValue:
          type: number
          description: Current register value after change
          example: 24.0
        timestamp:
          type: string
          format: date-time
          description: ISO 8601 timestamp when change was detected
          example: "2023-10-27T14:30:52.123Z"
        changeType:
          type: string
          enum: [value_change, first_read, reconnect]
          description: Type of change detected
          example: "value_change"
        source:
          type: string
          enum: [known, discovered]
          description: Whether register was predefined or dynamically found
          example: "known"
      required: [id, registerAddress, newValue, timestamp, changeType, source]

    RegisterMetadata:
      type: object
      properties:
        name:
          type: string
          nullable: true
          description: Human-readable name
          example: "Room Temperature"
        unit:
          type: string
          nullable: true
          description: Unit of measurement
          example: "°C"
        writable:
          type: boolean
          description: Whether register accepts write operations
          example: false
        scaling:
          type: number
          minimum: 0
          exclusiveMinimum: true
          description: Multiplication factor for display value
          example: 0.1
        confidence:
          type: number
          minimum: 0
          maximum: 1
          description: Discovery confidence score
          example: 0.85
        category:
          type: string
          enum: [temperature, control, status, unknown]
          description: Inferred register type
          example: "temperature"
      required: [writable, scaling, confidence, category]

    Register:
      type: object
      properties:
        address:
          type: integer
          minimum: 1
          maximum: 65535
          description: Modbus register address
          example: 1001
        currentValue:
          type: number
          description: Latest known value
          example: 24.0
        dataType:
          type: string
          enum: [int16, uint16, int32, uint32, float]
          description: Data interpretation
          example: "uint16"
        lastChanged:
          type: string
          format: date-time
          nullable: true
          description: ISO 8601 timestamp of last change
          example: "2023-10-27T14:30:52.123Z"
        changeHistory:
          type: array
          items:
            $ref: '#/components/schemas/RegisterChangeEvent'
          maxItems: 50
          description: Recent change events (max 50)
        isMonitored:
          type: boolean
          description: Whether actively polling this register
          example: true
        metadata:
          $ref: '#/components/schemas/RegisterMetadata'
      required: [address, currentValue, dataType, changeHistory, isMonitored, metadata]

    SessionConfiguration:
      type: object
      properties:
        pollingInterval:
          type: integer
          minimum: 100
          description: Milliseconds between register reads
          example: 2000
        debounceDelay:
          type: integer
          minimum: 0
          description: Milliseconds to wait before reporting rapid changes
          example: 100
        maxChangeHistory:
          type: integer
          minimum: 1
          maximum: 50
          description: Maximum change events to retain
          example: 50
        autoDiscovery:
          type: boolean
          description: Whether to enable dynamic register discovery
          example: true
        highlightDuration:
          type: integer
          minimum: 1
          description: Milliseconds to highlight changes in UI
          example: 3000
      required: [pollingInterval, debounceDelay, maxChangeHistory, autoDiscovery, highlightDuration]

    MonitoringSession:
      type: object
      properties:
        sessionId:
          type: string
          description: Unique session identifier
          example: "session_20231027_140000"
        startTime:
          type: string
          format: date-time
          description: ISO 8601 timestamp when monitoring started
          example: "2023-10-27T14:00:00.000Z"
        endTime:
          type: string
          format: date-time
          nullable: true
          description: ISO 8601 timestamp when monitoring stopped
          example: null
        mode:
          type: string
          enum: [basic, enhanced, demo]
          description: Monitoring mode used
          example: "enhanced"
        registersMonitored:
          type: array
          items:
            type: integer
            minimum: 1
            maximum: 65535
          description: Array of register addresses being monitored
          example: [1001, 1002, 1045, 1046]
        totalChanges:
          type: integer
          minimum: 0
          description: Count of all change events in this session
          example: 42
        configuration:
          $ref: '#/components/schemas/SessionConfiguration'
      required: [sessionId, startTime, mode, registersMonitored, totalChanges, configuration]

    # WebSocket Message Types
    ChangeNotification:
      type: object
      properties:
        type:
          type: string
          enum: [change_notification]
          description: Message type identifier
        event:
          $ref: '#/components/schemas/RegisterChangeEvent'
        sessionId:
          type: string
          description: Associated monitoring session
          example: "session_20231027_140000"
        timestamp:
          type: string
          format: date-time
          description: Server timestamp when message was sent
          example: "2023-10-27T14:30:52.456Z"
      required: [type, event, sessionId, timestamp]

    ChangeHistoryRequest:
      type: object
      properties:
        type:
          type: string
          enum: [change_history_request]
          description: Message type identifier
        registerAddress:
          type: integer
          minimum: 1
          maximum: 65535
          nullable: true
          description: Specific register (null for all)
          example: 1001
        since:
          type: string
          format: date-time
          nullable: true
          description: ISO 8601 timestamp for changes after this time
          example: "2023-10-27T14:00:00.000Z"
        limit:
          type: integer
          minimum: 1
          maximum: 1000
          description: Maximum number of events to return
          example: 50
      required: [type, limit]

    ChangeHistoryResponse:
      type: object
      properties:
        type:
          type: string
          enum: [change_history_response]
          description: Message type identifier
        events:
          type: array
          items:
            $ref: '#/components/schemas/RegisterChangeEvent'
          description: Array of change events
        totalCount:
          type: integer
          minimum: 0
          description: Total available events
          example: 127
        requestId:
          type: string
          description: Correlation ID for request
          example: "req_20231027_143052"
      required: [type, events, totalCount, requestId]

    SessionStatusUpdate:
      type: object
      properties:
        type:
          type: string
          enum: [session_status]
          description: Message type identifier
        session:
          $ref: '#/components/schemas/MonitoringSession'
        activeRegisters:
          type: integer
          minimum: 0
          description: Count of registers being monitored
          example: 12
        changesPerMinute:
          type: number
          minimum: 0
          description: Recent change frequency
          example: 3.7
      required: [type, session, activeRegisters, changesPerMinute]

    ErrorMessage:
      type: object
      properties:
        type:
          type: string
          enum: [error]
          description: Message type identifier
        code:
          type: string
          description: Error code
          example: "INVALID_REGISTER_ADDRESS"
        message:
          type: string
          description: Human-readable error message
          example: "Register address 70000 is outside valid range"
        timestamp:
          type: string
          format: date-time
          description: Server timestamp when error occurred
          example: "2023-10-27T14:30:52.789Z"
      required: [type, code, message, timestamp]

paths: {}  # WebSocket API doesn't use traditional REST paths